In [4]:
import pandas as pd

In [5]:
#data={"Pateint_ID","Age","Surgery_Type"}

In [6]:
#df=pd.DataFrame(data)

In [7]:
#print(df)

In [8]:
data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],
    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],
    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],
    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"],
    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],
    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],
    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

In [9]:
df = pd.DataFrame(data)

In [10]:
print(df)

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180
5       P106   68   Nizamabad              PTCA                     150
6       P107   29   Hyderabad      Appendectomy                      70
7       P108   52    Warangal   Cholecystectomy                      95
8       P109   47   Hyderabad     Hernia Repair                     120
9       P110   73  Karimnagar  Knee Replacement                     200

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
2                    1      Emergency
3                    3        Planned
4                    5        Planned
5                    4      Emergency
6                    1      Emergency
7                    2        Planned
8                    3        Planned
9                    6        Planned

#Q1.

In [11]:
print(df.head(5))

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
2                    1      Emergency
3                    3        Planned
4                    5        Planned

#Q.2

In [12]:
 print(df[["Patient_ID","City","Surgery_Type","Admission_Type"]])

  Patient_ID        City      Surgery_Type Admission_Type
0       P101   Hyderabad   Cholecystectomy        Planned
1       P102    Warangal              CABG      Emergency
2       P103   Hyderabad      Appendectomy      Emergency
3       P104  Vijayawada     Hernia Repair        Planned
4       P105   Hyderabad  Knee Replacement        Planned
5       P106   Nizamabad              PTCA      Emergency
6       P107   Hyderabad      Appendectomy      Emergency
7       P108    Warangal   Cholecystectomy        Planned
8       P109   Hyderabad     Hernia Repair        Planned
9       P110  Karimnagar  Knee Replacement        Planned

#Q3.

In [13]:
df.loc[df["Admission_Type"]=="Emergency"]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency

#Q4.

In [14]:
df.loc[df["Operation_Duration_Min"]>150]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
1,P102,62,Warangal,CABG,240,7,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

#Q5.

In [15]:
df.loc[df["City"]=="Hyderabad",["Patient_ID","Age","Surgery_Type","Admission_Type"]]

  Patient_ID  Age      Surgery_Type Admission_Type
0       P101   45   Cholecystectomy        Planned
2       P103   34      Appendectomy      Emergency
4       P105   41  Knee Replacement        Planned
6       P107   29      Appendectomy      Emergency
8       P109   47     Hernia Repair        Planned

#Q6.

In [16]:
df["Operation_Duration_Min"].mean()

np.float64(133.0)

#Q7.

In [17]:
df["Operation_Duration_Min"].max()

240

#Q8.

In [18]:
df["Operation_Duration_Min"].max(),["Patient_ID","Surgery_Type","Operation_Duration_Min"]

(240, ['Patient_ID', 'Surgery_Type', 'Operation_Duration_Min'])

#Q9.

In [19]:
df.loc[(df["Operation_Duration_Min"]>100) & (df["Length_of_Stay_Days"]>3),["Patient_ID","Surgery_Type","Operation_Duration_Min","Length_of_Stay_Days"]]

  Patient_ID      Surgery_Type  Operation_Duration_Min  Length_of_Stay_Days
1       P102              CABG                     240                    7
4       P105  Knee Replacement                     180                    5
5       P106              PTCA                     150                    4
9       P110  Knee Replacement                     200                    6

#Q10.

In [20]:
df.loc[(df["Admission_Type"]=="Emergency") & (df["Operation_Duration_Min"]>100),["Patient_ID","Surgery_Type","Operation_Duration_Min","Admission_Type"]]

  Patient_ID Surgery_Type  Operation_Duration_Min Admission_Type
1       P102         CABG                     240      Emergency
5       P106         PTCA                     150      Emergency

#PART-C :

In [21]:
df.loc[(df["Operation_Duration_Min"]>100) & (df["Length_of_Stay_Days"]>3),["Patient_ID","Surgery_Type"]]

  Patient_ID      Surgery_Type
1       P102              CABG
4       P105  Knee Replacement
5       P106              PTCA
9       P110  Knee Replacement

In [2]:
import pandas as pd

df = pd.read_csv("healthcare_dataset.csv")

df.head()

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P001,36,Nashik,Urological,85,4,Urgent
1,P002,43,Kolhapur,Dental,102,7,Elective
2,P003,50,Akola,Orthopedic,119,10,Emergency
3,P004,57,Mumbai,Gastrointestinal,136,3,Urgent
4,P005,64,Aurangabad,Ophthalmology,153,6,Elective

In [3]:
df.shape

(100, 7)